<?php

namespace Container2oRP5bu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Api_Validator_OrderNotEmptyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius.api.validator.order_not_empty' shared service.
     *
     * @return \Sylius\Bundle\ApiBundle\Validator\Constraints\OrderNotEmptyValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/Validator/Constraints/OrderNotEmptyValidator.php';

        return $container->privates['sylius.api.validator.order_not_empty'] = new \Sylius\Bundle\ApiBundle\Validator\Constraints\OrderNotEmptyValidator(($container->services['sylius.repository.order'] ?? $container->getSylius_Repository_OrderService()));
    }
}
